version: '2'
services:
  influxdb:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    env_file: .env-db
  app:
    build: .
    links:
      - influxdb
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - INFLUXDB_HOST=influxdb
